### This notebook contains 1000 English article where each one has 50 character as a maximum length of words.

In [5]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from googletrans import Translator

%matplotlib inline
dataset = pd.read_csv('data/dataset.csv', sep='\t', header=None).applymap(str)
languages = dataset[dataset.columns[0]].unique()
categories = dataset[dataset.columns[1]].unique()
# Rename Dataset Columns
dataset.columns = ["language","label","text"]
dataset.head()
languagesData=[]
loc = 0
for i in languages:
    name = languages[loc]+"Data" 
    globals()[name] = pd.DataFrame( dataset[dataset.language == i])
    loc += 1
    
englishData = englishData[1:1000]


In [6]:

def lower_words(text):
    text = text.str.lower()
    return text

englishData['text'] = lower_words(englishData['text'])
input_str = englishData['text']
print(englishData.head())

import seaborn as sn
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import re
def remove_surl(text):
    text = text.apply(lambda x: re.split('https:\/\/.*', str(x))[0])
    return text

def remove_url(text):
    text = text.apply(lambda x: re.split('http:\/\/.*', str(x))[0])
    return text

englishData['text'] = remove_url(englishData['text'])
englishData['text'] = remove_surl(englishData['text'])

englishData.head()
def remove_numbers(text):
    text = text.str.replace('\d+', '')
    return text


englishData['text'] = remove_numbers(englishData['text'])
englishData.head()
def remove_punctuations(text):
    text = text.str.replace('[^\w\s]','')
    return text


englishData['text'] = remove_punctuations(englishData['text'])
englishData.head()

def remove_blank_space(col):
    col = col.str.strip()
    col = col.replace('\s+', ' ', regex=True)   
    return col


englishData['text'] = remove_blank_space(englishData.text)
englishData.head()
import nltk
from nltk.corpus import stopwords
from keras.preprocessing.text import Tokenizer
def remove_stop_words(text, stop):    
    text.apply(lambda x: [item for item in x if item not in stop])
    return text

stop = stopwords.words('english')
remove_stop_words(englishData['text'],stop)
englishData.head()

# from nltk.tokenize import word_tokenize
# from nltk.stem import PorterStemmer, WordNetLemmatizer

# def stem_sentences(sentence):
#     tokens = sentence.split()
#     stemmed_tokens = [porter_stemmer.stem(token) for token in tokens]
#     return ' '.join(stemmed_tokens)


# porter_stemmer = PorterStemmer()
# englishData['text'] = englishData['text'].apply(stem_sentences)
# englishData.head()



  language        label                                               text
1  english  advertising  trump asks sec to mull half-year corporate fil...
2  english  advertising  wall st. up on trade hopes, s&p equals longest...
3  english  advertising  asian shares hit one-year low on turkey, china...
4  english  advertising  asian stocks weaken as turkey worries weigh, d...
5  english  advertising  most asian shares edge up after wall st. gains...


language        label                                               text
1  english  advertising  trump asks sec to mull halfyear corporate fili...
2  english  advertising  wall st up on trade hopes sp equals longest bu...
3  english  advertising  asian shares hit oneyear low on turkey china w...
4  english  advertising  asian stocks weaken as turkey worries weigh do...
5  english  advertising  most asian shares edge up after wall st gains ...

In [7]:
df = pd.DataFrame(englishData["label"]) 
# pd.DataFrame(data=englishData["text"][1:10])
df["text"] = englishData['text'].str.split().str[1:50].str.join(" ")

translator = Translator()
mylist = list( df["text"])
df["Arabic"] = df.text.map(lambda x: translator.translate(x,  dest="ar").text)
df

label                                               text  \
1    advertising  asks sec to mull halfyear corporate filings vs...   
2    advertising  st up on trade hopes sp equals longest bull ru...   
3    advertising  shares hit oneyear low on turkey china worries...   
4    advertising  stocks weaken as turkey worries weigh dollar s...   
5    advertising  asian shares edge up after wall st gains but c...   
6    advertising  bid for tesla no formal offer no firm deals wi...   
7    advertising  st rallies on solid earnings uschina trade tal...   
8    advertising  says no opec member can take over its share of...   
9    advertising  courses in data science that could help you sn...   
10   advertising  ceo was told about emissions software months b...   
11   advertising  retail sales rise solidly productivity acceler...   
12   advertising  hires cfo after lengthy search paving way for ...   
13   advertising  shares fall as us tariff deadline on china loo...   
14   advertising  nikes th anniversary ad featuring colin kaeper...   
15   advertising  one officially launches with cheaper storage p...   
16   advertising  fund management adds popular tech names blackr...   
17   advertising  look at teslas ninemember boardtesla incs boar...   
18   advertising  accuses tesla of spying on employees at gigafa...   
19   advertising  tesla shareholders trimmed stakes last quarter...   
20   advertising  dragged lower by chip stocks energy stock bols...   
21   advertising  nvidia expands in artificial intelligence inte...   
22   advertising                                                      
23   advertising  peter elvys our god is holy new songpeter elvy...   
24   advertising  at that ittybitty little notchwhile it can be ...   
25   advertising  thetegaformer manchester united goalkeeper edw...   
26   advertising  of nigeria apc senators published list of nige...   
27   advertising  perceive the important thing to profitable ent...   
28   advertising  was not sent check your email addresses email ...   
29   advertising  tech news gaming star ninja sparks outrage by ...   
30   advertising  oil price the rivalry between saudi arabia and...   
..           ...                                                ...   
970     business  lanoothis week colorful projects are here to s...   
971     business  has upgraded its fullscreen mobile ad type wit...   
972     business  bring everything they need including food wate...   
973     business  singaporebased organization is launching a non...   
974     business  ceo was told about emissions software months b...   
975     business  dave davies shares a case study that shows how...   
976     gambling  the market for a lightly used boeing well your...   
977     gambling  for the best travel credit cards youve come to...   
978     gambling  will raise fees for checked bags cancellations...   
979     gambling  to avoid excess toll road charges for rental c...   
980     gambling  the best travel rewards credit cards to carry ...   
981     gambling  august author rick adkins commentstoday im goi...   
982     gambling  allthis post contains references to products f...   
983     gambling  allthis post contains references to products f...   
984     gambling  allthis post contains references to products f...   
985     gambling  dropping transfer partner from ultimate reward...   
986     gambling  star wars archives signature series checklist ...   
987     gambling  home strategy articles budget commander subjec...   
988     gambling  orange games back to school giveaway ends augu...   
989     gambling  monsters new e creature decks prehistoric rd d...   
990     gambling  just in case card can be used for many differe...   
991     gambling  kristiansen and his father klaus were searchin...   
992     gambling  everyonethank you to all who participated in o...   
993     gambling  baseball baseball rookie cards top juan soto r...   
994     gambling  stand behind all 

In [8]:
df["NewEnglish"] = df.Arabic.map(lambda x: translator.translate(x,  dest="en").text)

In [9]:
df

label                                               text  \
1    advertising  asks sec to mull halfyear corporate filings vs...   
2    advertising  st up on trade hopes sp equals longest bull ru...   
3    advertising  shares hit oneyear low on turkey china worries...   
4    advertising  stocks weaken as turkey worries weigh dollar s...   
5    advertising  asian shares edge up after wall st gains but c...   
6    advertising  bid for tesla no formal offer no firm deals wi...   
7    advertising  st rallies on solid earnings uschina trade tal...   
8    advertising  says no opec member can take over its share of...   
9    advertising  courses in data science that could help you sn...   
10   advertising  ceo was told about emissions software months b...   
11   advertising  retail sales rise solidly productivity acceler...   
12   advertising  hires cfo after lengthy search paving way for ...   
13   advertising  shares fall as us tariff deadline on china loo...   
14   advertising  nikes th anniversary ad featuring colin kaeper...   
15   advertising  one officially launches with cheaper storage p...   
16   advertising  fund management adds popular tech names blackr...   
17   advertising  look at teslas ninemember boardtesla incs boar...   
18   advertising  accuses tesla of spying on employees at gigafa...   
19   advertising  tesla shareholders trimmed stakes last quarter...   
20   advertising  dragged lower by chip stocks energy stock bols...   
21   advertising  nvidia expands in artificial intelligence inte...   
22   advertising                                                      
23   advertising  peter elvys our god is holy new songpeter elvy...   
24   advertising  at that ittybitty little notchwhile it can be ...   
25   advertising  thetegaformer manchester united goalkeeper edw...   
26   advertising  of nigeria apc senators published list of nige...   
27   advertising  perceive the important thing to profitable ent...   
28   advertising  was not sent check your email addresses email ...   
29   advertising  tech news gaming star ninja sparks outrage by ...   
30   advertising  oil price the rivalry between saudi arabia and...   
..           ...                                                ...   
970     business  lanoothis week colorful projects are here to s...   
971     business  has upgraded its fullscreen mobile ad type wit...   
972     business  bring everything they need including food wate...   
973     business  singaporebased organization is launching a non...   
974     business  ceo was told about emissions software months b...   
975     business  dave davies shares a case study that shows how...   
976     gambling  the market for a lightly used boeing well your...   
977     gambling  for the best travel credit cards youve come to...   
978     gambling  will raise fees for checked bags cancellations...   
979     gambling  to avoid excess toll road charges for rental c...   
980     gambling  the best travel rewards credit cards to carry ...   
981     gambling  august author rick adkins commentstoday im goi...   
982     gambling  allthis post contains references to products f...   
983     gambling  allthis post contains references to products f...   
984     gambling  allthis post contains references to products f...   
985     gambling  dropping transfer partner from ultimate reward...   
986     gambling  star wars archives signature series checklist ...   
987     gambling  home strategy articles budget commander subjec...   
988     gambling  orange games back to school giveaway ends augu...   
989     gambling  monsters new e creature decks prehistoric rd d...   
990     gambling  just in case card can be used for many differe...   
991     gambling  kristiansen and his father klaus were searchin...   
992     gambling  everyonethank you to all who participated in o...   
993     gambling  baseball baseball rookie cards top juan soto r...   
994     gambling  stand behind all 

In [16]:
DFpart1 = pd.DataFrame(df["label"]) 
DFpart1["text"] = df["text"]
DFpart1.head()

label                                               text
1  advertising  asks sec to mull halfyear corporate filings vs...
2  advertising  st up on trade hopes sp equals longest bull ru...
3  advertising  shares hit oneyear low on turkey china worries...
4  advertising  stocks weaken as turkey worries weigh dollar s...
5  advertising  asian shares edge up after wall st gains but c...

In [17]:
DFpart2 = pd.DataFrame(df["label"]) 
DFpart2["text"] = df["NewEnglish"]
DFpart2.head()

label                                               text
1  advertising  Asked again to look at half-year corporate req...
2  advertising  Deceleration in business hopes: sp equals the ...
3  advertising  Chinese stocks fall to their lowest levels wit...
4  advertising  Asian stocks weaken as Turkey worries about do...
5  advertising  Asian stocks rise after Wall Street gains, but...

In [18]:
frames = [DFpart1, DFpart2]

In [19]:
dfMerged = pd.concat(frames)

In [23]:
len(dfMerged)

1998

In [26]:
print(dfMerged[dfMerged.columns[0]].unique())
print("Number of classes")
print(len(dfMerged[dfMerged.columns[0]].unique()))

['advertising' 'agriculture' 'animation' 'arts_and_crafts' 'entertainment'
 'astrology' 'vehicles' 'games' 'books_and_literature' 'business'
 'gambling']
Number of classes
11


In [35]:
#Import the model
from model import myfunc

### The concatenated Dataframe of the original English text and the translated text

In [31]:
myfunc(dfMerged,11)

         label                                               text
1  advertising  asks sec to mull halfyear corporate filings vs...
2  advertising  st up on trade hopes sp equals longest bull ru...
3  advertising  shares hit oneyear low on turkey china worries...
4  advertising  stocks weaken as turkey worries weigh dollar s...
5  advertising  asian shares edge up after wall st gains but c...
[   1  952 1454   73 2145 3621  640    6   40  215  167 3622 1251  116
    1  438    4 3621  640    2   40  215  111   26 1454 2146   10 2147
  295    1  193  215   36 2148   22    1  760    2  761    3 1455  541
    0    0    0    0    0    0    0    0    0    0    0    0    0    0
    0    0    0    0    0    0    0    0    0    0    0    0    0    0
    0    0    0    0    0    0    0    0    0    0    0    0    0    0
    0    0    0    0    0    0    0    0    0    0    0    0    0    0
    0    0]
[[1. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [1. 0. 0. ... 

### The dataset without the concatenation of the  translated rows 

In [32]:
OriginalDF = pd.DataFrame(df["label"]) 

In [33]:
OriginalDF["text"]= df["text"]

In [34]:
myfunc(OriginalDF,11)

         label                                               text
1  advertising  asks sec to mull halfyear corporate filings vs...
2  advertising  st up on trade hopes sp equals longest bull ru...
3  advertising  shares hit oneyear low on turkey china worries...
4  advertising  stocks weaken as turkey worries weigh dollar s...
5  advertising  asian shares edge up after wall st gains but c...
[3584 3585 3586 2198  239  220 3587  296 2199  726 1471  101   53 3588
  726 1471   28    3   17 2199  726 1471   16   52    6   26   54   15
   47    2   28    3   17   16   51    2   48    4   17   38   55   45
    2   16   61   64    2   68   73    0    0    0    0    0    0    0
    0    0    0    0    0    0    0    0    0    0    0    0    0    0
    0    0    0    0    0    0    0    0    0    0    0    0    0    0
    0    0    0    0    0    0    0    0    0    0    0    0    0    0
    0    0]
[[0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [1. 0. 0. ... 

<b><i> Conclusion: 

The Experiment result after the round trip translation is: 
    
Training Accuracy: 0.1068

Testing Accuracy:  0.0740
    
The Model Results without using the translation is:

Training Accuracy: 0.1041

Testing Accuracy:  0.0760 <b> <i>